/**
 * BVG 2025 Konstanten – Re-export aus zentralem swissVorsorge2025.ts
 * Quelle: ZHAW Vorsorgesystem Schweiz Update 2025
 */
import { BVG_GRENZWERTE_2025, BVG_LEISTUNGEN_2025, SAEULE_3A_2025 } from './swissVorsorge2025'

export const BVG_2026 = {
  COORDINATION_DEDUCTION: BVG_GRENZWERTE_2025.KOORDINATIONSABZUG,
  ENTRY_THRESHOLD:        BVG_GRENZWERTE_2025.EINTRITTSSCHWELLE,
  MAX_INSURED_SALARY:     BVG_GRENZWERTE_2025.MAX_PFLICHTIGER_LOHN,
  MIN_INTEREST_RATE:      BVG_LEISTUNGEN_2025.MINDESTZINSSATZ,
  MIN_CONVERSION_RATE:    BVG_LEISTUNGEN_2025.MINDESTUMWANDLUNGSSATZ,
  MAX_3A_WITH_PK:         SAEULE_3A_2025.MAX_BEITRAG_MIT_PK,
  MAX_3A_WITHOUT_PK:      SAEULE_3A_2025.MAX_BEITRAG_OHNE_PK,
} as const
