// Merged into pkConstants.ts — re-export for backwards compatibility
import { PK_CONSTANTS } from './pkConstants'

export const BVG_2026 = {
  COORDINATION_DEDUCTION: PK_CONSTANTS.COORDINATION_DEDUCTION_2026,
  ENTRY_THRESHOLD: PK_CONSTANTS.ENTRY_THRESHOLD_2026,
  MAX_INSURED_SALARY: PK_CONSTANTS.BVG_MAX_INSURED_SALARY,
  MIN_INTEREST_RATE: PK_CONSTANTS.BVG_MIN_INTEREST_RATE,
  MIN_CONVERSION_RATE: PK_CONSTANTS.BVG_MIN_CONVERSION_RATE,
  MAX_3A_WITH_PK: PK_CONSTANTS.MAX_3A_WITH_PK,
  MAX_3A_WITHOUT_PK: PK_CONSTANTS.MAX_3A_WITHOUT_PK,
} as const
